FROM ubuntu
ADD  index.html  /test_dir/add.html
COPY index.html  /test_dir/copy.html
ADD  https://github.com/kubernetes/kubernetes/blob/master/LICENSE /test_dir/
ADD  add_data.tgz /test_dir/
COPY copy_data.tgz /test_dir/

